Mongo Replica set - Add replicaMemberConfig to replica instance
nodkz/mongodb-memory-server pull request #508
Opened 2021-07-18 14:24 UTC by nhuanhoangduc

## Related Issues

- #1

2021-07-18 16:00 UTC, hasezoey requested changes
looking good, just one thing

2021-07-18 16:07 UTC, nhuanhoangduc commented on packages/mongodb-memory-server-core/src/util/MongoInstance.ts
> +// Ref: https://docs.mongodb.com/manual/reference/replica-configuration/#replica-set-configuration-document-example
I will update tsdoc in detail

2021-07-19 00:06 UTC, nhuanhoangduc commented on packages/mongodb-memory-server-core/src/util/MongoInstance.ts
> +// Ref: https://docs.mongodb.com/manual/reference/replica-configuration/#replica-set-configuration-document-example
Hi @hasezoey, I have updated tsdoc and unit test for this PR, please give me your feedbacks then I will improve this one. Thanks

2021-07-19 09:25 UTC, hasezoey commented
btw, does this PR have something to do with #209 ?

2021-07-19 09:31 UTC, hasezoey approved these changes
thanks for add this, code and tests look good, but i will wait to merge until https://github.com/nodkz/mongodb-memory-server/pull/508#issuecomment-882395863 is answered

2021-07-19 10:08 UTC, nhuanhoangduc commented
> btw, does this PR have something to do with #209 ?

I have checked mongo document version 4.4 and 5.0, there is a change in configuration to delay a replica set member:
For version 4.4: set options.slaveDelay = number
For version 5.x: set options.secondaryDelaySecs = number
My thought is we need to support both version (4.x and 5.x) since Mongodb 5.0 has ben release some days ago. I am going to add `slaveDelay` option to handle version 4.x

2021-07-19 10:33 UTC, hasezoey requested changes

2021-07-19 10:33 UTC, hasezoey commented on packages/mongodb-memory-server-core/src/util/MongoInstance.ts
> +   * @deprecated For mongodb 5.x, use `secondaryDelaySecs` instead.
could this be removed? at least for as long as 4.0.x is the default for this package

2021-07-19 10:37 UTC, hasezoey approved these changes

2021-07-19 10:41 UTC, merged